[kafka output] Rand integer partitioner
spotify/ffwd pull request #71
Opened 2018-06-04 15:36 UTC by nezdolik

2018-06-04 18:09 UTC, udoprog commented on modules/kafka/src/main/java/com/spotify/ffwd/kafka/KafkaPartitioner.java
Must add it here for it to work in configuration.

2018-06-04 18:10 UTC, udoprog requested changes

2018-06-04 18:10 UTC, udoprog commented on modules/kafka/src/main/java/com/spotify/ffwd/kafka/KafkaPartitioner.java
> +    class RandInt implements KafkaPartitioner {
Must add to `@JsonSubTypes` above for it to work in configuration.

2018-06-05 09:19 UTC, nezdolik commented
applied review comment @udoprog

2018-06-05 11:05 UTC, udoprog commented on modules/kafka/src/main/java/com/spotify/ffwd/kafka/KafkaPartitioner.java
> +    @JsonSubTypes.Type(value = KafkaPartitioner.RandInt.class, name = "randint")
name should probably be just `random`. `int` is just implementation detail.

2018-06-05 11:36 UTC, udoprog approved these changes

2018-06-05 11:45 UTC, merged